### PR TITLE
Vectortile

### PR DESCRIPTION
**Pull request by SumedhArani**

### CODE REVIEW

**Comment by bondhugula** [comment]
Can you make changes to follow  doc/CodingStyle (esp. braces for for loops)?

**Comment by SumedhArani** [comment]
Yes. 
I will also update the readme file for the autotilesize branch ASAP.

**Comment by bondhugula** [comment]
If you are issuing a pull request, please wait for my comments before merging!

~ Uday

________________________________________

**Comment by SumedhArani** [comment]
I am extremely sorry. Should I revert it back, so it is easy for you to check the diff?

**Comment by bondhugula** [comment]
No, it's fine for now - just commit changes to conform to the coding style.

~ Uday
________________________________________

**Comment by SumedhArani** [comment]
@bondhugula ,
I have made the changes to the code, now conforming to suggesting coding guidelines.

**Pull request merged**
