### PR TITLE
minor change in README.md ~ make checking pluto

### PR DESCRIPTION
**Pull request by czartur**
There is no rule for 'make check-pluto' but for 'make test'.

### CODE REVIEW

**Comment by czartur** [comment]
But it is not present in the stable version 0.11.4.

**Comment by bondhugula** [comment]
> But it is not present in the stable version 0.11.4.

But this is the git version far ahead of 0.11.4. What we add here has to be consistent with the current state of the repo.

**Comment by czartur** [comment]
> But this is the git version far ahead of 0.11.4. What we add here has to be consistent with the current state of the repo.

I understand, but there are two sections in the readme: one for the stable release and one for the git version.
 
 However, 'make check-pluto' is written in both even if it only works with the dev version.

**Comment by bondhugula** [comment]
> > But this is the git version far ahead of 0.11.4. What we add here has to be consistent with the current state of the repo.
> 
> I understand, but there are two sections in the readme: one for the stable release and one for the git version.
> 
> However, 'make check-pluto' is written in both even if it only works with the dev version.

Sorry about that, you are right.

**Review by bondhugula — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
